### ISSUE TITLE
can we resize image before uploading it ?

### ISSUE THREAD

**Issue by amoldorkar-ezest** [jkuri/ng2-uploader#37]
I want to upload an image with 74 x 74 size.

**Comment by ohader** [comment]
In general doing image manipulation on the server side seems to be better. Client's image processing might result in poor results since only basic maths for scaling is involved here.

Anyways, a possible solution might be to intercept the `FileList` before uploading, read the local file using `FileReader` and perform the actual image manipulation using a temporary `HTMLCanvasElement` and it's possibilities to export base64 encoded data (`canvas.toDataURL('image/png')`). That result would then be submitted to the server using `xhr`.
