### ISSUE TITLE
Support for dropping files on element

### ISSUE THREAD

**Issue by mwijnands** [jkuri/ng2-uploader#8]
First of all thanks for this great but simple library.

I'd like to see support for creating drop zones to drop files. Would be nice!

**Comment by jkuri** [comment]
Hi. Thanks, no problem. I plan to implement that in the near future.

**Comment by innovative1** [comment]
+1

**Comment by jkuri** [comment]
I added the drop zones support. Use directive NgFileDrop exactly as NgFileSelect. I will add documentation later.

**Comment by mwijnands** [comment]
Nice!

I wonder why did you rewrite commit history? Now we can't see the changes... And you made some big changes even to the project structure.

**Comment by jkuri** [comment]
Sorry for that. It was previously based as a `angular-cli` project and it has demo in it. Since we temporarily removed `ng install` command I decided to rewrite this lib to have only files that are actually needed. It will soon be possible to install this library with the new `ng install` command and current files in this repo are all the files that will be needed for that.
